version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: |
            ls -la ~/
            pwd
            sudo apt-get update
            sudo apt-get install curl -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo apt-get install unzip -y
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Validate packer config
          command: | 
            packer validate \
            -var "aws_access_key=${AWS_ACCESS_KEY}" \
            -var "aws_secret_key=${AWS_SECRET_KEY}" \
            -var "aws_region=${AWS_REGION}" \
            -var "ami_users=${AMI_USERS}" \
            -var "source_ami=${SOURCE_AMI}" \
            -var "subnet_id=${SUBNET_ID}" \
            ubuntu-ami.json

      - run:
          name: Build packer config
          command: | 
            packer build \
            -var "aws_access_key=${AWS_ACCESS_KEY}" \
            -var "aws_secret_key=${AWS_SECRET_KEY}" \
            -var "aws_region=${AWS_REGION}" \
            -var "ami_users=${AMI_USERS}" \
            -var "source_ami=${SOURCE_AMI}" \
            -var "subnet_id=${SUBNET_ID}" \
            ubuntu-ami.json

          
workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  